export const BABY_SIZE_EMOJI: Record<string, string> = {
  'Poppy Seed':       '🌱',
  'Sesame Seed':      '🌾',
  'Lentil':           '🌱',
  'Blueberry':        '🫐',
  'Sweet Pea':        '🌿',
  'Kidney Bean':      '🫘',
  'Grape':            '🍇',
  'Strawberry':       '🍓',
  'Lime':             '🍋',
  'Plum':             '🍑',
  'Peach':            '🍑',
  'Lemon':            '🍋',
  'Apple':            '🍎',
  'Avocado':          '🥑',
  'Pear':             '🍐',
  'Sweet Potato':     '🍠',
  'Mango':            '🥭',
  'Banana':           '🍌',
  'Carrot':           '🥕',
  'Spaghetti Squash': '🎃',
  'Grapefruit':       '🍊',
  'Corn':             '🌽',
  'Rutabaga':         '🌰',
  'Scallion':         '🌿',
  'Cauliflower':      '🥦',
  'Eggplant':         '🍆',
  'Butternut Squash': '🎃',
  'Cabbage':          '🥬',
  'Coconut':          '🥥',
  'Jicama':           '🥔',
  'Pineapple':        '🍍',
  'Cantaloupe':       '🍈',
  'Honeydew':         '🍈',
  'Romaine Lettuce':  '🥬',
  'Swiss Chard':      '🥬',
  'Leek':             '🌿',
  'Watermelon':       '🍉',
  'Small Pumpkin':    '🎃',
}
