insert into pregnancy_weeks (week_number, title, description) values
  (1,  'Week 1',  'Your journey begins. Conception has occurred and your body is preparing for an incredible 40 weeks.'),
  (2,  'Week 2',  'Your body is ovulating. The fertilized egg is traveling toward the uterus.'),
  (3,  'Week 3',  'The embryo is the size of a poppy seed. Cell division is well underway.'),
  (4,  'Week 4',  'Baby is the size of a poppy seed. The embryo implants in the uterus this week.'),
  (5,  'Week 5',  'Baby is the size of a sesame seed. The heart and circulatory system are beginning to form.'),
  (6,  'Week 6',  'Baby is the size of a lentil. The tiny heart starts beating — about 150 times per minute!'),
  (7,  'Week 7',  'Baby is the size of a blueberry. The brain and face are developing rapidly.'),
  (8,  'Week 8',  'Baby is the size of a kidney bean. Fingers and toes are beginning to form.'),
  (9,  'Week 9',  'Baby is the size of a grape. All essential organs have begun to develop.'),
  (10, 'Week 10', 'Baby is the size of a strawberry. Tiny fingernails are forming.'),
  (11, 'Week 11', 'Baby is the size of a fig. Baby can open and close their fists.'),
  (12, 'Week 12', 'Baby is the size of a lime. The risk of miscarriage drops significantly this week.'),
  (13, 'Week 13', 'Baby is the size of a peapod. You''ve reached the second trimester!'),
  (14, 'Week 14', 'Baby is the size of a lemon. Baby can now make facial expressions.'),
  (15, 'Week 15', 'Baby is the size of an apple. Baby is forming taste buds.'),
  (16, 'Week 16', 'Baby is the size of an avocado. You may start to feel baby''s first movements.'),
  (17, 'Week 17', 'Baby is the size of a pear. Baby''s skeleton is hardening from cartilage to bone.'),
  (18, 'Week 18', 'Baby is the size of a sweet potato. This is a common time for an anatomy ultrasound.'),
  (19, 'Week 19', 'Baby is the size of a mango. Baby is covered in a waxy coating called vernix.'),
  (20, 'Week 20', 'Baby is the size of a banana. Halfway there! Baby can hear your voice now.'),
  (21, 'Week 21', 'Baby is the size of a carrot. Baby''s movements are becoming stronger and more coordinated.'),
  (22, 'Week 22', 'Baby is the size of a papaya. Baby''s senses are developing — touch, taste, sight, and hearing.'),
  (23, 'Week 23', 'Baby is the size of a large mango. Baby can recognize your voice and may respond to it.'),
  (24, 'Week 24', 'Baby is the size of an ear of corn. Baby has a chance of survival if born now.'),
  (25, 'Week 25', 'Baby is the size of a cauliflower. Baby is gaining fat and their skin is becoming less wrinkled.'),
  (26, 'Week 26', 'Baby is the size of a scallion. Baby''s eyes are beginning to open.'),
  (27, 'Week 27', 'Baby is the size of a head of lettuce. You''re entering the third trimester!'),
  (28, 'Week 28', 'Baby is the size of an eggplant. Baby can blink and has eyelashes now.'),
  (29, 'Week 29', 'Baby is the size of a butternut squash. Baby''s brain is developing rapidly.'),
  (30, 'Week 30', 'Baby is the size of a large cabbage. Baby is putting on about half a pound per week.'),
  (31, 'Week 31', 'Baby is the size of a coconut. Baby''s lungs are maturing quickly.'),
  (32, 'Week 32', 'Baby is the size of a jicama. Baby is practicing breathing movements.'),
  (33, 'Week 33', 'Baby is the size of a pineapple. Baby''s bones are hardening except the skull.'),
  (34, 'Week 34', 'Baby is the size of a butternut squash. Baby''s central nervous system is maturing.'),
  (35, 'Week 35', 'Baby is the size of a honeydew melon. Baby''s kidneys are fully developed.'),
  (36, 'Week 36', 'Baby is the size of a head of romaine lettuce. Baby is considered early term this week.'),
  (37, 'Week 37', 'Baby is the size of a winter melon. Baby is full term! Ready to meet you soon.'),
  (38, 'Week 38', 'Baby is the size of a pumpkin. Baby''s organs are fully developed and ready for life outside the womb.'),
  (39, 'Week 39', 'Baby is the size of a watermelon. Baby is ready — just waiting for the perfect moment.'),
  (40, 'Week 40', 'Baby is the size of a small pumpkin. Your due date has arrived. Welcome to the world!');
